using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("ActiveLucene.Net")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2010")]
[assembly: AssemblyVersionAttribute("0.1.10.5241")]
[assembly: AssemblyFileVersionAttribute("0.1.10.5241")]
[assembly: AssemblyInformationalVersionAttribute("0.1")]

