using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("ActiveLucene.Net")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2010-2011")]
[assembly: AssemblyVersionAttribute("0.1.1417.5202")]
[assembly: AssemblyFileVersionAttribute("0.1.1417.5202")]
[assembly: AssemblyInformationalVersionAttribute("0.1")]

