using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("ActiveLucene.Net")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2010-2012")]
[assembly: AssemblyVersionAttribute("0.2.2612.5201")]
[assembly: AssemblyFileVersionAttribute("0.2.2612.5201")]
[assembly: AssemblyInformationalVersionAttribute("0.2")]

