//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.3.1233.18853")]
[assembly: System.Reflection.AssemblyFileVersion("0.3.1233.18853")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.3")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2013")]
[assembly: System.Reflection.AssemblyProduct("ActiveLucene.Net")]
[assembly: System.Reflection.AssemblyDescription("Built 8/21/2013 6:54:15 AM")]


